# Generated by Django 4.2.4 on 2023-08-26 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Filmler'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Kisi', 'verbose_name_plural': 'Kisiler'},
        ),
        migrations.AddField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Ozet'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_name',
            field=models.CharField(max_length=50, verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Baslik'),
        ),
        migrations.AlterField(
            model_name='person',
            name='duty_type',
            field=models.CharField(choices=[('1', 'Crew'), ('2', 'Cast'), ('3', 'Director'), ('4', 'Writer')], max_length=1, verbose_name='Gorev'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Cinsiyet'),
        ),
    ]
