# Generated by Django 4.2.4 on 2023-09-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_image_cover_alter_movie_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slide_img',
            field=models.FileField(default='', upload_to='images'),
        ),
    ]
