# Generated by Django 4.2.4 on 2023-09-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_slide_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_name',
            field=models.FileField(default='', upload_to='images_person'),
        ),
    ]
