# Generated by Django 4.2.4 on 2023-09-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ratting',
            field=models.CharField(choices=[('1', '1 Star'), ('2', '2 Star'), ('3', '3 Star'), ('4', '4 Star'), ('5', '5 Star')], max_length=1, null=True),
        ),
    ]
