# Generated by Django 4.2.4 on 2023-09-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movie_options_remove_movie_slide_img_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Filmler'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Kapak resmi', 'verbose_name_plural': 'Kapak resimleri'},
        ),
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
